import type { ActivityMode, PersonaId, CampaignTemplate } from '../types';

// ─── Campaign definitions ─────────────────────────────────────────────────────
// 4 personas × 10 campaigns each. Each campaign has up to 7 mission templates.
// When generating for a user, templates are matched 1:1 to preferredDays in order,
// cycling through templates if there are more days than templates.
//
// Mission Briefing + in-run TTS: missionsStore merges each row with
// narrativeForCampaignMission (see src/utils/campaignMissionNarrative.ts).
// Optional per-row overrides: add description and/or audioCues on a template.

const GHOST_CAMPAIGNS: CampaignTemplate[] = [
  {
    index: 1,
    title: 'FIRST STEPS',
    subtitle: 'Dust off your boots. The road begins here.',
    missionTemplates: [
      {
        type: 'easy',
        title: 'Perimeter Walk',
        subtitle: 'Light movement. Survey the zone.',
        targetDistanceKm: 0.5,
        targetDurationMin: 8,
        targetCyclingDistanceKm: 1.5,
        targetCyclingDurationMin: 8,
        xpReward: 20,
      },
      {
        type: 'recovery',
        title: 'Slow Recon',
        subtitle: 'Easy movement. No pressure.',
        targetDistanceKm: 0.5,
        targetDurationMin: 8,
        targetCyclingDistanceKm: 1.5,
        targetCyclingDurationMin: 8,
        xpReward: 20,
      },
      {
        type: 'easy',
        title: 'Grid Check',
        subtitle: 'Keep moving, keep breathing.',
        targetDistanceKm: 0.5,
        targetDurationMin: 8,
        targetCyclingDistanceKm: 1.5,
        targetCyclingDurationMin: 8,
        xpReward: 20,
      },
    ],
  },
  {
    index: 2,
    title: 'MOVEMENT PROTOCOL',
    subtitle: 'Consistency is the mission.',
    missionTemplates: [
      {
        type: 'easy',
        title: 'Zone Patrol',
        subtitle: 'Cover the ground. Feel the rhythm.',
        targetDistanceKm: 0.75,
        targetDurationMin: 10,
        targetCyclingDistanceKm: 2,
        targetCyclingDurationMin: 10,
        xpReward: 25,
      },
      {
        type: 'recovery',
        title: 'Easy Circuit',
        subtitle: 'Light legs, clear head.',
        targetDistanceKm: 0.75,
        targetDurationMin: 10,
        targetCyclingDistanceKm: 2,
        targetCyclingDurationMin: 10,
        xpReward: 25,
      },
      {
        type: 'easy',
        title: 'Sector Walk',
        subtitle: 'Build the habit, not the pain.',
        targetDistanceKm: 0.75,
        targetDurationMin: 10,
        targetCyclingDistanceKm: 2,
        targetCyclingDurationMin: 10,
        xpReward: 25,
      },
    ],
  },
  {
    index: 3,
    title: 'FIRST SIGNAL',
    subtitle: 'Your body is beginning to respond.',
    missionTemplates: [
      {
        type: 'easy',
        title: 'Signal Walk',
        subtitle: 'Push just a little further.',
        targetDistanceKm: 1,
        targetDurationMin: 13,
        targetCyclingDistanceKm: 2.5,
        targetCyclingDurationMin: 12,
        xpReward: 30,
      },
      {
        type: 'recovery',
        title: 'Scout Pass',
        subtitle: 'Keep it gentle. You earn rest.',
        targetDistanceKm: 1,
        targetDurationMin: 13,
        targetCyclingDistanceKm: 2.5,
        targetCyclingDurationMin: 12,
        xpReward: 30,
      },
      {
        type: 'easy',
        title: 'Morning Sweep',
        subtitle: 'Start the engine. Let it idle.',
        targetDistanceKm: 1,
        targetDurationMin: 13,
        targetCyclingDistanceKm: 2.5,
        targetCyclingDurationMin: 12,
        xpReward: 30,
      },
    ],
  },
  {
    index: 4,
    title: 'FREQUENCY RISE',
    subtitle: 'Distance grows. So do you.',
    missionTemplates: [
      {
        type: 'easy',
        title: 'Power Line Run',
        subtitle: 'Jog when you can. Walk when you need.',
        targetDistanceKm: 1.25,
        targetDurationMin: 16,
        targetCyclingDistanceKm: 3,
        targetCyclingDurationMin: 14,
        xpReward: 35,
      },
      {
        type: 'recovery',
        title: 'Perimeter Jog',
        subtitle: 'Easy and purposeful.',
        targetDistanceKm: 1.25,
        targetDurationMin: 16,
        targetCyclingDistanceKm: 3,
        targetCyclingDurationMin: 14,
        xpReward: 35,
      },
      {
        type: 'easy',
        title: 'Grid Restore',
        subtitle: 'Motion is medicine.',
        targetDistanceKm: 1.25,
        targetDurationMin: 16,
        targetCyclingDistanceKm: 3,
        targetCyclingDurationMin: 14,
        xpReward: 35,
      },
    ],
  },
  {
    index: 5,
    title: 'STEADY STATE',
    subtitle: 'You are becoming a runner.',
    missionTemplates: [
      {
        type: 'easy',
        title: 'Zone Jog',
        subtitle: 'No stopping this time.',
        targetDistanceKm: 1.5,
        targetDurationMin: 18,
        targetCyclingDistanceKm: 3.5,
        targetCyclingDurationMin: 16,
        xpReward: 40,
      },
      {
        type: 'easy',
        title: 'Field Run',
        subtitle: 'Keep the pace steady.',
        targetDistanceKm: 1.5,
        targetDurationMin: 18,
        targetCyclingDistanceKm: 3.5,
        targetCyclingDurationMin: 16,
        xpReward: 40,
      },
      {
        type: 'recovery',
        title: 'Recovery Lap',
        subtitle: 'Protect the streak.',
        targetDistanceKm: 1.5,
        targetDurationMin: 18,
        targetCyclingDistanceKm: 3.5,
        targetCyclingDurationMin: 16,
        xpReward: 40,
      },
    ],
  },
  {
    index: 6,
    title: 'SECTOR EXPANSION',
    subtitle: 'New territory unlocked.',
    missionTemplates: [
      {
        type: 'easy',
        title: 'Outer Ring',
        subtitle: 'Push further from base.',
        targetDistanceKm: 2,
        targetDurationMin: 22,
        targetCyclingDistanceKm: 4.5,
        targetCyclingDurationMin: 20,
        xpReward: 50,
      },
      {
        type: 'tempo',
        title: 'Signal Boost',
        subtitle: 'Pick up the pace briefly.',
        targetDistanceKm: 2,
        targetDurationMin: 22,
        targetCyclingDistanceKm: 4.5,
        targetCyclingDurationMin: 20,
        xpReward: 50,
      },
      {
        type: 'recovery',
        title: 'Easy Loop',
        subtitle: 'Keep the engine warm.',
        targetDistanceKm: 2,
        targetDurationMin: 22,
        targetCyclingDistanceKm: 4.5,
        targetCyclingDurationMin: 20,
        xpReward: 50,
      },
    ],
  },
  {
    index: 7,
    title: 'CONSISTENT RUNNER',
    subtitle: 'The habit is set. Push forward.',
    missionTemplates: [
      {
        type: 'easy',
        title: 'Morning Grid',
        subtitle: 'Consistent. Reliable. Dangerous.',
        targetDistanceKm: 2.25,
        targetDurationMin: 25,
        targetCyclingDistanceKm: 5,
        targetCyclingDurationMin: 22,
        xpReward: 55,
      },
      {
        type: 'tempo',
        title: 'Surge Drill',
        subtitle: 'Brief hard effort. Big reward.',
        targetDistanceKm: 2.25,
        targetDurationMin: 25,
        targetCyclingDistanceKm: 5,
        targetCyclingDurationMin: 22,
        xpReward: 55,
      },
      {
        type: 'recovery',
        title: 'Reset Run',
        subtitle: 'Flush the fatigue.',
        targetDistanceKm: 2.25,
        targetDurationMin: 25,
        targetCyclingDistanceKm: 5,
        targetCyclingDurationMin: 22,
        xpReward: 55,
      },
    ],
  },
  {
    index: 8,
    title: 'ZONE DEFENDER',
    subtitle: 'You protect what you restore.',
    missionTemplates: [
      {
        type: 'easy',
        title: 'Defense Patrol',
        subtitle: 'Hold the sector.',
        targetDistanceKm: 2.5,
        targetDurationMin: 27,
        targetCyclingDistanceKm: 5.5,
        targetCyclingDurationMin: 24,
        xpReward: 60,
      },
      {
        type: 'tempo',
        title: 'Tower Push',
        subtitle: 'Sustained pace. Hold it.',
        targetDistanceKm: 2.5,
        targetDurationMin: 27,
        targetCyclingDistanceKm: 5.5,
        targetCyclingDurationMin: 24,
        xpReward: 60,
      },
      {
        type: 'recovery',
        title: 'Field Scout',
        subtitle: 'Recover smart.',
        targetDistanceKm: 2.5,
        targetDurationMin: 27,
        targetCyclingDistanceKm: 5.5,
        targetCyclingDurationMin: 24,
        xpReward: 60,
      },
    ],
  },
  {
    index: 9,
    title: 'LONG HAUL',
    subtitle: 'Beyond the wire.',
    missionTemplates: [
      {
        type: 'long',
        title: 'Deep Recon',
        subtitle: 'Longer than before. You can do this.',
        targetDistanceKm: 3,
        targetDurationMin: 32,
        targetCyclingDistanceKm: 7,
        targetCyclingDurationMin: 28,
        xpReward: 70,
      },
      {
        type: 'easy',
        title: 'Grid Restore',
        subtitle: 'Steady and strong.',
        targetDistanceKm: 3,
        targetDurationMin: 32,
        targetCyclingDistanceKm: 7,
        targetCyclingDurationMin: 28,
        xpReward: 70,
      },
      {
        type: 'recovery',
        title: 'Perimeter Hold',
        subtitle: 'Rest is part of the mission.',
        targetDistanceKm: 3,
        targetDurationMin: 32,
        targetCyclingDistanceKm: 7,
        targetCyclingDurationMin: 28,
        xpReward: 70,
      },
    ],
  },
  {
    index: 10,
    title: 'ZONE RESTORED',
    subtitle: 'Ghost protocol complete.',
    missionTemplates: [
      {
        type: 'long',
        title: 'Final Sweep',
        subtitle: 'Last patrol. Leave nothing behind.',
        targetDistanceKm: 3,
        targetDurationMin: 35,
        targetCyclingDistanceKm: 8,
        targetCyclingDurationMin: 30,
        xpReward: 80,
      },
      {
        type: 'tempo',
        title: 'Signal Lock',
        subtitle: 'One final push.',
        targetDistanceKm: 3,
        targetDurationMin: 35,
        targetCyclingDistanceKm: 8,
        targetCyclingDurationMin: 30,
        xpReward: 80,
      },
      {
        type: 'easy',
        title: 'Zone Clear',
        subtitle: 'You made it. The ghost lives.',
        targetDistanceKm: 3,
        targetDurationMin: 35,
        targetCyclingDistanceKm: 8,
        targetCyclingDurationMin: 30,
        xpReward: 80,
      },
    ],
  },
];

const SCOUT_CAMPAIGNS: CampaignTemplate[] = [
  {
    index: 1,
    title: 'BASE CAMP',
    subtitle: 'Establish your operational tempo.',
    missionTemplates: [
      {
        type: 'easy',
        title: 'Sector Jog',
        subtitle: 'Find your legs.',
        targetDistanceKm: 2,
        targetDurationMin: 15,
        targetCyclingDistanceKm: 5,
        targetCyclingDurationMin: 15,
        xpReward: 30,
      },
      {
        type: 'recovery',
        title: 'Easy Loop',
        subtitle: 'Build without breaking.',
        targetDistanceKm: 2,
        targetDurationMin: 15,
        targetCyclingDistanceKm: 5,
        targetCyclingDurationMin: 15,
        xpReward: 30,
      },
      {
        type: 'easy',
        title: 'Morning Run',
        subtitle: 'Consistent beats intense.',
        targetDistanceKm: 2,
        targetDurationMin: 15,
        targetCyclingDistanceKm: 5,
        targetCyclingDurationMin: 15,
        xpReward: 30,
      },
    ],
  },
  {
    index: 2,
    title: 'FIELD TRAINING',
    subtitle: 'Push the baseline.',
    missionTemplates: [
      {
        type: 'easy',
        title: 'Zone Run',
        subtitle: 'Cover the ground.',
        targetDistanceKm: 2.5,
        targetDurationMin: 18,
        targetCyclingDistanceKm: 6,
        targetCyclingDurationMin: 18,
        xpReward: 35,
      },
      {
        type: 'tempo',
        title: 'Signal Rush',
        subtitle: 'Brief push, big result.',
        targetDistanceKm: 2.5,
        targetDurationMin: 18,
        targetCyclingDistanceKm: 6,
        targetCyclingDurationMin: 18,
        xpReward: 40,
      },
      {
        type: 'recovery',
        title: 'Scout Flush',
        subtitle: 'Keep legs fresh.',
        targetDistanceKm: 2.5,
        targetDurationMin: 18,
        targetCyclingDistanceKm: 6,
        targetCyclingDurationMin: 18,
        xpReward: 30,
      },
    ],
  },
  {
    index: 3,
    title: 'PATTERN LOCK',
    subtitle: 'Your body learns the rhythm.',
    missionTemplates: [
      {
        type: 'easy',
        title: 'Grid Patrol',
        subtitle: 'Make it feel easy.',
        targetDistanceKm: 3,
        targetDurationMin: 22,
        targetCyclingDistanceKm: 7,
        targetCyclingDurationMin: 20,
        xpReward: 40,
      },
      {
        type: 'tempo',
        title: 'Frequency Push',
        subtitle: 'Hold a harder effort.',
        targetDistanceKm: 3,
        targetDurationMin: 22,
        targetCyclingDistanceKm: 7,
        targetCyclingDurationMin: 20,
        xpReward: 45,
      },
      {
        type: 'recovery',
        title: 'Recon Light',
        subtitle: 'Protect the streak.',
        targetDistanceKm: 3,
        targetDurationMin: 22,
        targetCyclingDistanceKm: 7,
        targetCyclingDurationMin: 20,
        xpReward: 35,
      },
    ],
  },
  {
    index: 4,
    title: 'DISTANCE PUSH',
    subtitle: 'Run further than last week.',
    missionTemplates: [
      {
        type: 'easy',
        title: 'Long Sector',
        subtitle: 'More ground covered.',
        targetDistanceKm: 3.5,
        targetDurationMin: 25,
        targetCyclingDistanceKm: 8,
        targetCyclingDurationMin: 22,
        xpReward: 45,
      },
      {
        type: 'interval',
        title: 'Anomaly Drill',
        subtitle: 'Push and recover.',
        targetDistanceKm: 3.5,
        targetDurationMin: 25,
        targetCyclingDistanceKm: 8,
        targetCyclingDurationMin: 22,
        xpReward: 55,
      },
      {
        type: 'recovery',
        title: 'Scout Patrol',
        subtitle: 'Easy and deliberate.',
        targetDistanceKm: 3.5,
        targetDurationMin: 25,
        targetCyclingDistanceKm: 8,
        targetCyclingDurationMin: 22,
        xpReward: 40,
      },
    ],
  },
  {
    index: 5,
    title: 'OPERATIONALLY READY',
    subtitle: 'Consistent enough to be counted on.',
    missionTemplates: [
      {
        type: 'easy',
        title: 'Outer Sweep',
        subtitle: 'Good pace, good form.',
        targetDistanceKm: 4,
        targetDurationMin: 28,
        targetCyclingDistanceKm: 9,
        targetCyclingDurationMin: 24,
        xpReward: 50,
      },
      {
        type: 'tempo',
        title: 'Signal Boost',
        subtitle: 'Faster on this one.',
        targetDistanceKm: 4,
        targetDurationMin: 28,
        targetCyclingDistanceKm: 9,
        targetCyclingDurationMin: 24,
        xpReward: 60,
      },
      {
        type: 'long',
        title: 'Supply Route',
        subtitle: 'The longest yet. Pace yourself.',
        targetDistanceKm: 4,
        targetDurationMin: 28,
        targetCyclingDistanceKm: 9,
        targetCyclingDurationMin: 24,
        xpReward: 55,
      },
    ],
  },
  {
    index: 6,
    title: 'SECTOR COMMAND',
    subtitle: 'You control the tempo.',
    missionTemplates: [
      {
        type: 'tempo',
        title: 'Comm Rush',
        subtitle: 'Hold a challenging pace.',
        targetDistanceKm: 5,
        targetDurationMin: 32,
        targetCyclingDistanceKm: 11,
        targetCyclingDurationMin: 28,
        xpReward: 65,
      },
      {
        type: 'easy',
        title: 'Zone Patrol',
        subtitle: 'Keep it moving.',
        targetDistanceKm: 5,
        targetDurationMin: 32,
        targetCyclingDistanceKm: 11,
        targetCyclingDurationMin: 28,
        xpReward: 55,
      },
      {
        type: 'interval',
        title: 'Surge Protocol',
        subtitle: 'Speed bursts activate.',
        targetDistanceKm: 5,
        targetDurationMin: 32,
        targetCyclingDistanceKm: 11,
        targetCyclingDurationMin: 28,
        xpReward: 70,
      },
    ],
  },
  {
    index: 7,
    title: 'LONG MARCH',
    subtitle: 'Go the distance.',
    missionTemplates: [
      {
        type: 'long',
        title: 'Cross-Zone Haul',
        subtitle: 'Cover serious ground.',
        targetDistanceKm: 6,
        targetDurationMin: 38,
        targetCyclingDistanceKm: 13,
        targetCyclingDurationMin: 32,
        xpReward: 75,
      },
      {
        type: 'easy',
        title: 'Recovery Lap',
        subtitle: 'Fresh legs for the next push.',
        targetDistanceKm: 6,
        targetDurationMin: 38,
        targetCyclingDistanceKm: 13,
        targetCyclingDurationMin: 32,
        xpReward: 65,
      },
      {
        type: 'tempo',
        title: 'Network Surge',
        subtitle: 'Hold a faster pace.',
        targetDistanceKm: 6,
        targetDurationMin: 38,
        targetCyclingDistanceKm: 13,
        targetCyclingDurationMin: 32,
        xpReward: 75,
      },
    ],
  },
  {
    index: 8,
    title: 'FIELD PROVEN',
    subtitle: 'The scout earns their patch.',
    missionTemplates: [
      {
        type: 'easy',
        title: 'Perimeter Run',
        subtitle: 'Smooth and confident.',
        targetDistanceKm: 6.5,
        targetDurationMin: 42,
        targetCyclingDistanceKm: 14,
        targetCyclingDurationMin: 36,
        xpReward: 80,
      },
      {
        type: 'interval',
        title: 'Emergency Sprint',
        subtitle: 'Go hard, then recover.',
        targetDistanceKm: 6.5,
        targetDurationMin: 42,
        targetCyclingDistanceKm: 14,
        targetCyclingDurationMin: 36,
        xpReward: 90,
      },
      {
        type: 'long',
        title: 'Outer Zone Run',
        subtitle: 'Take it all the way.',
        targetDistanceKm: 6.5,
        targetDurationMin: 42,
        targetCyclingDistanceKm: 14,
        targetCyclingDurationMin: 36,
        xpReward: 85,
      },
    ],
  },
  {
    index: 9,
    title: 'DEEP FIELD OPS',
    subtitle: 'Scout boundaries pushed.',
    missionTemplates: [
      {
        type: 'long',
        title: 'Endurance March',
        subtitle: 'Far and focused.',
        targetDistanceKm: 7,
        targetDurationMin: 46,
        targetCyclingDistanceKm: 15,
        targetCyclingDurationMin: 40,
        xpReward: 90,
      },
      {
        type: 'tempo',
        title: 'Signal Hold',
        subtitle: 'Sustained hard effort.',
        targetDistanceKm: 7,
        targetDurationMin: 46,
        targetCyclingDistanceKm: 15,
        targetCyclingDurationMin: 40,
        xpReward: 95,
      },
      {
        type: 'recovery',
        title: 'Rest and Hold',
        subtitle: 'Recovery is an order.',
        targetDistanceKm: 7,
        targetDurationMin: 46,
        targetCyclingDistanceKm: 15,
        targetCyclingDurationMin: 40,
        xpReward: 80,
      },
    ],
  },
  {
    index: 10,
    title: 'SCOUT COMPLETE',
    subtitle: 'All zones surveyed.',
    missionTemplates: [
      {
        type: 'long',
        title: 'Final Survey',
        subtitle: 'Prove what you are.',
        targetDistanceKm: 8,
        targetDurationMin: 52,
        targetCyclingDistanceKm: 17,
        targetCyclingDurationMin: 44,
        xpReward: 100,
      },
      {
        type: 'tempo',
        title: 'Tower Lock',
        subtitle: 'Hold the pace to the end.',
        targetDistanceKm: 8,
        targetDurationMin: 52,
        targetCyclingDistanceKm: 17,
        targetCyclingDurationMin: 44,
        xpReward: 100,
      },
      {
        type: 'interval',
        title: 'Final Surge',
        subtitle: 'Go out strong.',
        targetDistanceKm: 8,
        targetDurationMin: 52,
        targetCyclingDistanceKm: 17,
        targetCyclingDurationMin: 44,
        xpReward: 100,
      },
    ],
  },
];

const OPERATIVE_CAMPAIGNS: CampaignTemplate[] = [
  {
    index: 1,
    title: 'ACTIVE DUTY',
    subtitle: 'Sharpen the blade.',
    missionTemplates: [
      {
        type: 'easy',
        title: 'Zone Run',
        subtitle: 'Comfortable hard.',
        targetDistanceKm: 4,
        targetDurationMin: 25,
        targetCyclingDistanceKm: 10,
        targetCyclingDurationMin: 24,
        xpReward: 50,
      },
      {
        type: 'tempo',
        title: 'Signal Rush',
        subtitle: 'Push the pace.',
        targetDistanceKm: 4,
        targetDurationMin: 25,
        targetCyclingDistanceKm: 10,
        targetCyclingDurationMin: 24,
        xpReward: 60,
      },
      {
        type: 'recovery',
        title: 'Recon Loop',
        subtitle: 'Earn recovery.',
        targetDistanceKm: 4,
        targetDurationMin: 25,
        targetCyclingDistanceKm: 10,
        targetCyclingDurationMin: 24,
        xpReward: 45,
      },
    ],
  },
  {
    index: 2,
    title: 'NETWORK RESTORE',
    subtitle: 'Build speed and stamina.',
    missionTemplates: [
      {
        type: 'tempo',
        title: 'Comm Push',
        subtitle: 'Hold 80% effort.',
        targetDistanceKm: 5,
        targetDurationMin: 30,
        targetCyclingDistanceKm: 12,
        targetCyclingDurationMin: 27,
        xpReward: 65,
      },
      {
        type: 'interval',
        title: 'Surge Drill',
        subtitle: 'Speed bursts engage.',
        targetDistanceKm: 5,
        targetDurationMin: 30,
        targetCyclingDistanceKm: 12,
        targetCyclingDurationMin: 27,
        xpReward: 75,
      },
      {
        type: 'long',
        title: 'Supply Run',
        subtitle: 'Build your base.',
        targetDistanceKm: 5,
        targetDurationMin: 30,
        targetCyclingDistanceKm: 12,
        targetCyclingDurationMin: 27,
        xpReward: 65,
      },
    ],
  },
  {
    index: 3,
    title: 'FIELD PRESSURE',
    subtitle: 'Performance under load.',
    missionTemplates: [
      {
        type: 'interval',
        title: 'Anomaly Surge',
        subtitle: 'Max effort, max return.',
        targetDistanceKm: 6,
        targetDurationMin: 35,
        targetCyclingDistanceKm: 14,
        targetCyclingDurationMin: 30,
        xpReward: 80,
      },
      {
        type: 'tempo',
        title: 'Hold Frequency',
        subtitle: 'Comfortable hard pace.',
        targetDistanceKm: 6,
        targetDurationMin: 35,
        targetCyclingDistanceKm: 14,
        targetCyclingDurationMin: 30,
        xpReward: 80,
      },
      {
        type: 'easy',
        title: 'Base Reset',
        subtitle: 'Recover and rebuild.',
        targetDistanceKm: 6,
        targetDurationMin: 35,
        targetCyclingDistanceKm: 14,
        targetCyclingDurationMin: 30,
        xpReward: 65,
      },
    ],
  },
  {
    index: 4,
    title: 'LONG RANGE',
    subtitle: 'Extend your operational radius.',
    missionTemplates: [
      {
        type: 'long',
        title: 'Deep Zone Run',
        subtitle: 'More distance, same focus.',
        targetDistanceKm: 7,
        targetDurationMin: 42,
        targetCyclingDistanceKm: 16,
        targetCyclingDurationMin: 36,
        xpReward: 85,
      },
      {
        type: 'tempo',
        title: 'Signal Hold',
        subtitle: 'Push the threshold.',
        targetDistanceKm: 7,
        targetDurationMin: 42,
        targetCyclingDistanceKm: 16,
        targetCyclingDurationMin: 36,
        xpReward: 90,
      },
      {
        type: 'recovery',
        title: 'Easy Sweep',
        subtitle: 'Recover to perform.',
        targetDistanceKm: 7,
        targetDurationMin: 42,
        targetCyclingDistanceKm: 16,
        targetCyclingDurationMin: 36,
        xpReward: 75,
      },
    ],
  },
  {
    index: 5,
    title: 'COMBAT READY',
    subtitle: 'Forged in repetition.',
    missionTemplates: [
      {
        type: 'tempo',
        title: 'Frequency Hold',
        subtitle: 'Threshold session.',
        targetDistanceKm: 8,
        targetDurationMin: 48,
        targetCyclingDistanceKm: 18,
        targetCyclingDurationMin: 40,
        xpReward: 95,
      },
      {
        type: 'interval',
        title: 'Emergency Surge',
        subtitle: 'Go to the well.',
        targetDistanceKm: 8,
        targetDurationMin: 48,
        targetCyclingDistanceKm: 18,
        targetCyclingDurationMin: 40,
        xpReward: 100,
      },
      {
        type: 'long',
        title: 'Endurance Route',
        subtitle: 'Pace and distance.',
        targetDistanceKm: 8,
        targetDurationMin: 48,
        targetCyclingDistanceKm: 18,
        targetCyclingDurationMin: 40,
        xpReward: 95,
      },
    ],
  },
  {
    index: 6,
    title: 'EXTENDED OPS',
    subtitle: 'Range increases. So does your strength.',
    missionTemplates: [
      {
        type: 'long',
        title: 'Outer Zone March',
        subtitle: 'Long and controlled.',
        targetDistanceKm: 9,
        targetDurationMin: 54,
        targetCyclingDistanceKm: 20,
        targetCyclingDurationMin: 44,
        xpReward: 100,
      },
      {
        type: 'interval',
        title: 'Surge Protocol',
        subtitle: 'Sprint blocks activate.',
        targetDistanceKm: 9,
        targetDurationMin: 54,
        targetCyclingDistanceKm: 20,
        targetCyclingDurationMin: 44,
        xpReward: 110,
      },
      {
        type: 'recovery',
        title: 'Zone Hold',
        subtitle: 'Smart recovery.',
        targetDistanceKm: 9,
        targetDurationMin: 54,
        targetCyclingDistanceKm: 20,
        targetCyclingDurationMin: 44,
        xpReward: 90,
      },
    ],
  },
  {
    index: 7,
    title: 'TEMPO MASTERY',
    subtitle: 'Speed is a weapon.',
    missionTemplates: [
      {
        type: 'tempo',
        title: 'Signal Lock',
        subtitle: 'Hold pace all the way.',
        targetDistanceKm: 9,
        targetDurationMin: 50,
        targetCyclingDistanceKm: 20,
        targetCyclingDurationMin: 44,
        xpReward: 100,
      },
      {
        type: 'interval',
        title: 'Final Surge',
        subtitle: 'Break the ceiling.',
        targetDistanceKm: 9,
        targetDurationMin: 50,
        targetCyclingDistanceKm: 20,
        targetCyclingDurationMin: 44,
        xpReward: 115,
      },
      {
        type: 'long',
        title: 'Range Run',
        subtitle: 'Expand your territory.',
        targetDistanceKm: 9,
        targetDurationMin: 50,
        targetCyclingDistanceKm: 20,
        targetCyclingDurationMin: 44,
        xpReward: 105,
      },
    ],
  },
  {
    index: 8,
    title: 'HIGH OUTPUT',
    subtitle: 'Push your peak.',
    missionTemplates: [
      {
        type: 'long',
        title: 'Cross-Zone Marathon Prep',
        subtitle: 'Almost there. Keep building.',
        targetDistanceKm: 10,
        targetDurationMin: 60,
        targetCyclingDistanceKm: 22,
        targetCyclingDurationMin: 50,
        xpReward: 110,
      },
      {
        type: 'tempo',
        title: 'Full Frequency',
        subtitle: 'Push the ceiling.',
        targetDistanceKm: 10,
        targetDurationMin: 60,
        targetCyclingDistanceKm: 22,
        targetCyclingDurationMin: 50,
        xpReward: 120,
      },
      {
        type: 'interval',
        title: 'Anomaly Crush',
        subtitle: 'Speed and power.',
        targetDistanceKm: 10,
        targetDurationMin: 60,
        targetCyclingDistanceKm: 22,
        targetCyclingDurationMin: 50,
        xpReward: 125,
      },
    ],
  },
  {
    index: 9,
    title: 'SUSTAINED ASSAULT',
    subtitle: 'The body remembers this.',
    missionTemplates: [
      {
        type: 'long',
        title: 'Long Haul',
        subtitle: 'Distance is yours now.',
        targetDistanceKm: 11,
        targetDurationMin: 66,
        targetCyclingDistanceKm: 24,
        targetCyclingDurationMin: 54,
        xpReward: 120,
      },
      {
        type: 'interval',
        title: 'Surge Override',
        subtitle: 'Max output protocol.',
        targetDistanceKm: 11,
        targetDurationMin: 66,
        targetCyclingDistanceKm: 24,
        targetCyclingDurationMin: 54,
        xpReward: 130,
      },
      {
        type: 'tempo',
        title: 'Signal Domination',
        subtitle: 'Own the frequency.',
        targetDistanceKm: 11,
        targetDurationMin: 66,
        targetCyclingDistanceKm: 24,
        targetCyclingDurationMin: 54,
        xpReward: 125,
      },
    ],
  },
  {
    index: 10,
    title: 'OPERATIVE COMPLETE',
    subtitle: 'Ten campaigns. The world is saved.',
    missionTemplates: [
      {
        type: 'long',
        title: 'Final Operation',
        subtitle: 'Close it out. Leave nothing.',
        targetDistanceKm: 12,
        targetDurationMin: 72,
        targetCyclingDistanceKm: 26,
        targetCyclingDurationMin: 58,
        xpReward: 140,
      },
      {
        type: 'tempo',
        title: 'Last Signal',
        subtitle: 'Everything you have.',
        targetDistanceKm: 12,
        targetDurationMin: 72,
        targetCyclingDistanceKm: 26,
        targetCyclingDurationMin: 58,
        xpReward: 140,
      },
      {
        type: 'interval',
        title: 'Zone Domination',
        subtitle: 'Surge. Recover. Win.',
        targetDistanceKm: 12,
        targetDurationMin: 72,
        targetCyclingDistanceKm: 26,
        targetCyclingDurationMin: 58,
        xpReward: 140,
      },
    ],
  },
];

const VANGUARD_CAMPAIGNS: CampaignTemplate[] = [
  {
    index: 1,
    title: 'HARDENED ASSET',
    subtitle: 'High-intensity from day one.',
    missionTemplates: [
      {
        type: 'tempo',
        title: 'Opening Surge',
        subtitle: 'Set the tone.',
        targetDistanceKm: 8,
        targetDurationMin: 42,
        targetCyclingDistanceKm: 18,
        targetCyclingDurationMin: 38,
        xpReward: 90,
      },
      {
        type: 'interval',
        title: 'Anomaly Response',
        subtitle: 'Speed burst activate.',
        targetDistanceKm: 8,
        targetDurationMin: 42,
        targetCyclingDistanceKm: 18,
        targetCyclingDurationMin: 38,
        xpReward: 100,
      },
      {
        type: 'long',
        title: 'Range Extension',
        subtitle: 'Go long. Go fast.',
        targetDistanceKm: 8,
        targetDurationMin: 42,
        targetCyclingDistanceKm: 18,
        targetCyclingDurationMin: 38,
        xpReward: 95,
      },
      {
        type: 'recovery',
        title: 'Active Reset',
        subtitle: 'Recover to attack again.',
        targetDistanceKm: 8,
        targetDurationMin: 42,
        targetCyclingDistanceKm: 18,
        targetCyclingDurationMin: 38,
        xpReward: 80,
      },
    ],
  },
  {
    index: 2,
    title: 'SPEED PROTOCOL',
    subtitle: 'Build explosive pace.',
    missionTemplates: [
      {
        type: 'interval',
        title: 'Surge Overload',
        subtitle: 'Push the limits.',
        targetDistanceKm: 10,
        targetDurationMin: 50,
        targetCyclingDistanceKm: 22,
        targetCyclingDurationMin: 44,
        xpReward: 110,
      },
      {
        type: 'tempo',
        title: 'Threshold Lock',
        subtitle: 'Hold the line.',
        targetDistanceKm: 10,
        targetDurationMin: 50,
        targetCyclingDistanceKm: 22,
        targetCyclingDurationMin: 44,
        xpReward: 105,
      },
      {
        type: 'long',
        title: 'Foundation Run',
        subtitle: 'Aerobic base maintained.',
        targetDistanceKm: 10,
        targetDurationMin: 50,
        targetCyclingDistanceKm: 22,
        targetCyclingDurationMin: 44,
        xpReward: 105,
      },
    ],
  },
  {
    index: 3,
    title: 'LONG RANGE ASSAULT',
    subtitle: 'Cover serious distance.',
    missionTemplates: [
      {
        type: 'long',
        title: 'Deep Recon',
        subtitle: 'Far and controlled.',
        targetDistanceKm: 12,
        targetDurationMin: 60,
        targetCyclingDistanceKm: 26,
        targetCyclingDurationMin: 52,
        xpReward: 120,
      },
      {
        type: 'interval',
        title: 'Speed Block',
        subtitle: 'Hard blocks. Big reward.',
        targetDistanceKm: 12,
        targetDurationMin: 60,
        targetCyclingDistanceKm: 26,
        targetCyclingDurationMin: 52,
        xpReward: 130,
      },
      {
        type: 'tempo',
        title: 'Sustained Push',
        subtitle: 'High output over distance.',
        targetDistanceKm: 12,
        targetDurationMin: 60,
        targetCyclingDistanceKm: 26,
        targetCyclingDurationMin: 52,
        xpReward: 125,
      },
    ],
  },
  {
    index: 4,
    title: 'FORCE MULTIPLICATION',
    subtitle: 'Combined speed and endurance.',
    missionTemplates: [
      {
        type: 'long',
        title: 'Endurance Pass',
        subtitle: 'Aerobic power.',
        targetDistanceKm: 14,
        targetDurationMin: 70,
        targetCyclingDistanceKm: 30,
        targetCyclingDurationMin: 58,
        xpReward: 130,
      },
      {
        type: 'interval',
        title: 'Emergency Protocol',
        subtitle: 'Max output trigger.',
        targetDistanceKm: 14,
        targetDurationMin: 70,
        targetCyclingDistanceKm: 30,
        targetCyclingDurationMin: 58,
        xpReward: 145,
      },
      {
        type: 'tempo',
        title: 'Tower Override',
        subtitle: 'Lock the frequency.',
        targetDistanceKm: 14,
        targetDurationMin: 70,
        targetCyclingDistanceKm: 30,
        targetCyclingDurationMin: 58,
        xpReward: 140,
      },
    ],
  },
  {
    index: 5,
    title: 'PEAK CONDITIONING',
    subtitle: 'High-performance output.',
    missionTemplates: [
      {
        type: 'interval',
        title: 'Speed Mastery',
        subtitle: 'Hit new limits.',
        targetDistanceKm: 14,
        targetDurationMin: 65,
        targetCyclingDistanceKm: 30,
        targetCyclingDurationMin: 55,
        xpReward: 140,
      },
      {
        type: 'long',
        title: 'Zone March',
        subtitle: 'Endurance unlocked.',
        targetDistanceKm: 14,
        targetDurationMin: 65,
        targetCyclingDistanceKm: 30,
        targetCyclingDurationMin: 55,
        xpReward: 140,
      },
      {
        type: 'tempo',
        title: 'Full Frequency',
        subtitle: 'Sustained threshold.',
        targetDistanceKm: 14,
        targetDurationMin: 65,
        targetCyclingDistanceKm: 30,
        targetCyclingDurationMin: 55,
        xpReward: 140,
      },
    ],
  },
  {
    index: 6,
    title: 'TACTICAL ADVANCE',
    subtitle: 'Strategy and speed combined.',
    missionTemplates: [
      {
        type: 'long',
        title: 'Range Expansion',
        subtitle: 'Far and fast.',
        targetDistanceKm: 16,
        targetDurationMin: 80,
        targetCyclingDistanceKm: 34,
        targetCyclingDurationMin: 66,
        xpReward: 155,
      },
      {
        type: 'tempo',
        title: 'Surge Lock',
        subtitle: 'Hold the hard pace.',
        targetDistanceKm: 16,
        targetDurationMin: 80,
        targetCyclingDistanceKm: 34,
        targetCyclingDurationMin: 66,
        xpReward: 155,
      },
      {
        type: 'interval',
        title: 'Final Anomaly',
        subtitle: 'Suppress and advance.',
        targetDistanceKm: 16,
        targetDurationMin: 80,
        targetCyclingDistanceKm: 34,
        targetCyclingDurationMin: 66,
        xpReward: 165,
      },
    ],
  },
  {
    index: 7,
    title: 'ULTRA THRESHOLD',
    subtitle: 'The body beyond its limits.',
    missionTemplates: [
      {
        type: 'long',
        title: 'Ultra Prep',
        subtitle: 'Simulate race conditions.',
        targetDistanceKm: 18,
        targetDurationMin: 95,
        targetCyclingDistanceKm: 38,
        targetCyclingDurationMin: 78,
        xpReward: 165,
      },
      {
        type: 'interval',
        title: 'Speed Override',
        subtitle: 'Race-pace effort.',
        targetDistanceKm: 18,
        targetDurationMin: 95,
        targetCyclingDistanceKm: 38,
        targetCyclingDurationMin: 78,
        xpReward: 175,
      },
      {
        type: 'tempo',
        title: 'Signal Dominate',
        subtitle: 'Hold the threshold hard.',
        targetDistanceKm: 18,
        targetDurationMin: 95,
        targetCyclingDistanceKm: 38,
        targetCyclingDurationMin: 78,
        xpReward: 170,
      },
    ],
  },
  {
    index: 8,
    title: 'WORLD RESCUER',
    subtitle: 'Elite status confirmed.',
    missionTemplates: [
      {
        type: 'long',
        title: 'Marathon Recon',
        subtitle: 'Longest run of the campaign.',
        targetDistanceKm: 20,
        targetDurationMin: 110,
        targetCyclingDistanceKm: 44,
        targetCyclingDurationMin: 90,
        xpReward: 180,
      },
      {
        type: 'interval',
        title: 'Surge Crush',
        subtitle: 'Max power output.',
        targetDistanceKm: 20,
        targetDurationMin: 110,
        targetCyclingDistanceKm: 44,
        targetCyclingDurationMin: 90,
        xpReward: 190,
      },
      {
        type: 'tempo',
        title: 'Lock Frequency',
        subtitle: 'Zone restored. Keep pushing.',
        targetDistanceKm: 20,
        targetDurationMin: 110,
        targetCyclingDistanceKm: 44,
        targetCyclingDurationMin: 90,
        xpReward: 185,
      },
    ],
  },
  {
    index: 9,
    title: 'OMEGA PROTOCOL',
    subtitle: 'The final test before glory.',
    missionTemplates: [
      {
        type: 'long',
        title: 'Omega Run',
        subtitle: 'All zones. All effort.',
        targetDistanceKm: 22,
        targetDurationMin: 120,
        targetCyclingDistanceKm: 48,
        targetCyclingDurationMin: 100,
        xpReward: 200,
      },
      {
        type: 'interval',
        title: 'Alpha Surge',
        subtitle: 'Race to the end.',
        targetDistanceKm: 22,
        targetDurationMin: 120,
        targetCyclingDistanceKm: 48,
        targetCyclingDurationMin: 100,
        xpReward: 210,
      },
      {
        type: 'tempo',
        title: 'Signal Absolute',
        subtitle: 'Maximum sustained output.',
        targetDistanceKm: 22,
        targetDurationMin: 120,
        targetCyclingDistanceKm: 48,
        targetCyclingDurationMin: 100,
        xpReward: 205,
      },
    ],
  },
  {
    index: 10,
    title: 'VANGUARD COMPLETE',
    subtitle: 'The world is restored. You did this.',
    missionTemplates: [
      {
        type: 'long',
        title: 'Final Conquest',
        subtitle: 'Leave everything on the road.',
        targetDistanceKm: 24,
        targetDurationMin: 130,
        targetCyclingDistanceKm: 52,
        targetCyclingDurationMin: 108,
        xpReward: 220,
      },
      {
        type: 'interval',
        title: 'Victory Surge',
        subtitle: 'One last surge. Make it count.',
        targetDistanceKm: 24,
        targetDurationMin: 130,
        targetCyclingDistanceKm: 52,
        targetCyclingDurationMin: 108,
        xpReward: 225,
      },
      {
        type: 'tempo',
        title: 'Final Frequency',
        subtitle: 'The last signal. Forever online.',
        targetDistanceKm: 24,
        targetDurationMin: 130,
        targetCyclingDistanceKm: 52,
        targetCyclingDurationMin: 108,
        xpReward: 220,
      },
    ],
  },
];

const ELITE_CAMPAIGNS: CampaignTemplate[] = [
  {
    index: 1,
    title: 'ELITE ACTIVATION',
    subtitle: 'Sharpen the edge from day one.',
    missionTemplates: [
      {
        type: 'easy',
        title: 'Zone Run',
        subtitle: 'Warm up the machine.',
        targetDistanceKm: 6,
        targetDurationMin: 35,
        targetCyclingDistanceKm: 14,
        targetCyclingDurationMin: 30,
        xpReward: 70,
      },
      {
        type: 'tempo',
        title: 'Signal Rush',
        subtitle: 'Push the tempo.',
        targetDistanceKm: 6,
        targetDurationMin: 35,
        targetCyclingDistanceKm: 14,
        targetCyclingDurationMin: 30,
        xpReward: 80,
      },
      {
        type: 'interval',
        title: 'Surge Drill',
        subtitle: 'Speed blocks engage.',
        targetDistanceKm: 6,
        targetDurationMin: 35,
        targetCyclingDistanceKm: 14,
        targetCyclingDurationMin: 30,
        xpReward: 85,
      },
      {
        type: 'long',
        title: 'Range Check',
        subtitle: 'Go long. Stay controlled.',
        targetDistanceKm: 6,
        targetDurationMin: 35,
        targetCyclingDistanceKm: 14,
        targetCyclingDurationMin: 30,
        xpReward: 75,
      },
      {
        type: 'recovery',
        title: 'Active Reset',
        subtitle: 'Recover to attack again.',
        targetDistanceKm: 6,
        targetDurationMin: 35,
        targetCyclingDistanceKm: 14,
        targetCyclingDurationMin: 30,
        xpReward: 65,
      },
    ],
  },
  {
    index: 2,
    title: 'SPEED FOUNDATION',
    subtitle: 'Build explosive pace from the ground up.',
    missionTemplates: [
      {
        type: 'tempo',
        title: 'Threshold Push',
        subtitle: 'Hold 80% effort.',
        targetDistanceKm: 7,
        targetDurationMin: 40,
        targetCyclingDistanceKm: 16,
        targetCyclingDurationMin: 34,
        xpReward: 85,
      },
      {
        type: 'interval',
        title: 'Anomaly Response',
        subtitle: 'Speed burst activate.',
        targetDistanceKm: 7,
        targetDurationMin: 40,
        targetCyclingDistanceKm: 16,
        targetCyclingDurationMin: 34,
        xpReward: 90,
      },
      {
        type: 'easy',
        title: 'Base Patrol',
        subtitle: 'Aerobic base maintained.',
        targetDistanceKm: 7,
        targetDurationMin: 40,
        targetCyclingDistanceKm: 16,
        targetCyclingDurationMin: 34,
        xpReward: 75,
      },
      {
        type: 'long',
        title: 'Sector Run',
        subtitle: 'Distance confidence.',
        targetDistanceKm: 7,
        targetDurationMin: 40,
        targetCyclingDistanceKm: 16,
        targetCyclingDurationMin: 34,
        xpReward: 80,
      },
      {
        type: 'recovery',
        title: 'Recovery Hold',
        subtitle: 'Protect the engine.',
        targetDistanceKm: 7,
        targetDurationMin: 40,
        targetCyclingDistanceKm: 16,
        targetCyclingDurationMin: 34,
        xpReward: 70,
      },
    ],
  },
  {
    index: 3,
    title: 'TEMPO PROTOCOL',
    subtitle: 'Sustain a hard pace. Again and again.',
    missionTemplates: [
      {
        type: 'tempo',
        title: 'Frequency Lock',
        subtitle: 'Controlled hard effort.',
        targetDistanceKm: 8,
        targetDurationMin: 45,
        targetCyclingDistanceKm: 18,
        targetCyclingDurationMin: 38,
        xpReward: 90,
      },
      {
        type: 'interval',
        title: 'Surge Override',
        subtitle: 'Max output blocks.',
        targetDistanceKm: 8,
        targetDurationMin: 45,
        targetCyclingDistanceKm: 18,
        targetCyclingDurationMin: 38,
        xpReward: 100,
      },
      {
        type: 'long',
        title: 'Grid March',
        subtitle: 'Pace and distance combined.',
        targetDistanceKm: 8,
        targetDurationMin: 45,
        targetCyclingDistanceKm: 18,
        targetCyclingDurationMin: 38,
        xpReward: 90,
      },
      {
        type: 'easy',
        title: 'Zone Sweep',
        subtitle: 'Aerobic base run.',
        targetDistanceKm: 8,
        targetDurationMin: 45,
        targetCyclingDistanceKm: 18,
        targetCyclingDurationMin: 38,
        xpReward: 80,
      },
      {
        type: 'recovery',
        title: 'Smart Recovery',
        subtitle: 'Active flush session.',
        targetDistanceKm: 8,
        targetDurationMin: 45,
        targetCyclingDistanceKm: 18,
        targetCyclingDurationMin: 38,
        xpReward: 75,
      },
    ],
  },
  {
    index: 4,
    title: 'INTERVAL SURGE',
    subtitle: 'Speed is a weapon. Use it.',
    missionTemplates: [
      {
        type: 'interval',
        title: 'Anomaly Crush',
        subtitle: 'Push the speed ceiling.',
        targetDistanceKm: 9,
        targetDurationMin: 48,
        targetCyclingDistanceKm: 20,
        targetCyclingDurationMin: 42,
        xpReward: 105,
      },
      {
        type: 'tempo',
        title: 'Signal Sustain',
        subtitle: 'Hold the hard pace.',
        targetDistanceKm: 9,
        targetDurationMin: 48,
        targetCyclingDistanceKm: 20,
        targetCyclingDurationMin: 42,
        xpReward: 100,
      },
      {
        type: 'long',
        title: 'Deep Sector',
        subtitle: 'Aerobic endurance run.',
        targetDistanceKm: 9,
        targetDurationMin: 48,
        targetCyclingDistanceKm: 20,
        targetCyclingDurationMin: 42,
        xpReward: 95,
      },
      {
        type: 'easy',
        title: 'Field Patrol',
        subtitle: 'Easy movement, sharp mind.',
        targetDistanceKm: 9,
        targetDurationMin: 48,
        targetCyclingDistanceKm: 20,
        targetCyclingDurationMin: 42,
        xpReward: 85,
      },
      {
        type: 'recovery',
        title: 'Zone Reset',
        subtitle: 'Recover to perform.',
        targetDistanceKm: 9,
        targetDurationMin: 48,
        targetCyclingDistanceKm: 20,
        targetCyclingDurationMin: 42,
        xpReward: 80,
      },
    ],
  },
  {
    index: 5,
    title: 'LONG RANGE BUILD',
    subtitle: 'Endurance leads the way.',
    missionTemplates: [
      {
        type: 'long',
        title: 'Cross-Zone Run',
        subtitle: 'Serious ground covered.',
        targetDistanceKm: 10,
        targetDurationMin: 56,
        targetCyclingDistanceKm: 22,
        targetCyclingDurationMin: 48,
        xpReward: 110,
      },
      {
        type: 'interval',
        title: 'Speed Protocol',
        subtitle: 'Fast blocks, big reward.',
        targetDistanceKm: 10,
        targetDurationMin: 56,
        targetCyclingDistanceKm: 22,
        targetCyclingDurationMin: 48,
        xpReward: 115,
      },
      {
        type: 'tempo',
        title: 'Comm Push',
        subtitle: 'Threshold intensity.',
        targetDistanceKm: 10,
        targetDurationMin: 56,
        targetCyclingDistanceKm: 22,
        targetCyclingDurationMin: 48,
        xpReward: 110,
      },
      {
        type: 'easy',
        title: 'Outer Loop',
        subtitle: 'Comfortable hard.',
        targetDistanceKm: 10,
        targetDurationMin: 56,
        targetCyclingDistanceKm: 22,
        targetCyclingDurationMin: 48,
        xpReward: 95,
      },
      {
        type: 'recovery',
        title: 'Field Flush',
        subtitle: 'Smart rest. Earned rest.',
        targetDistanceKm: 10,
        targetDurationMin: 56,
        targetCyclingDistanceKm: 22,
        targetCyclingDurationMin: 48,
        xpReward: 90,
      },
    ],
  },
  {
    index: 6,
    title: 'THRESHOLD MASTERY',
    subtitle: 'Own the hard pace.',
    missionTemplates: [
      {
        type: 'tempo',
        title: 'Signal Domination',
        subtitle: 'Sustained threshold run.',
        targetDistanceKm: 11,
        targetDurationMin: 60,
        targetCyclingDistanceKm: 24,
        targetCyclingDurationMin: 52,
        xpReward: 120,
      },
      {
        type: 'interval',
        title: 'Surge Mastery',
        subtitle: 'Speed and control.',
        targetDistanceKm: 11,
        targetDurationMin: 60,
        targetCyclingDistanceKm: 24,
        targetCyclingDurationMin: 52,
        xpReward: 125,
      },
      {
        type: 'long',
        title: 'Range Extension',
        subtitle: 'Far and focused.',
        targetDistanceKm: 11,
        targetDurationMin: 60,
        targetCyclingDistanceKm: 24,
        targetCyclingDurationMin: 52,
        xpReward: 115,
      },
      {
        type: 'easy',
        title: 'Base Sweep',
        subtitle: 'Build the aerobic engine.',
        targetDistanceKm: 11,
        targetDurationMin: 60,
        targetCyclingDistanceKm: 24,
        targetCyclingDurationMin: 52,
        xpReward: 105,
      },
      {
        type: 'recovery',
        title: 'Hold Recovery',
        subtitle: 'Active reset protocol.',
        targetDistanceKm: 11,
        targetDurationMin: 60,
        targetCyclingDistanceKm: 24,
        targetCyclingDurationMin: 52,
        xpReward: 100,
      },
    ],
  },
  {
    index: 7,
    title: 'RACE PREP',
    subtitle: 'Simulate race conditions.',
    missionTemplates: [
      {
        type: 'long',
        title: 'Endurance Recon',
        subtitle: 'Race-pace effort sustained.',
        targetDistanceKm: 12,
        targetDurationMin: 64,
        targetCyclingDistanceKm: 26,
        targetCyclingDurationMin: 55,
        xpReward: 130,
      },
      {
        type: 'interval',
        title: 'Final Surge Prep',
        subtitle: 'Break through the ceiling.',
        targetDistanceKm: 12,
        targetDurationMin: 64,
        targetCyclingDistanceKm: 26,
        targetCyclingDurationMin: 55,
        xpReward: 135,
      },
      {
        type: 'tempo',
        title: 'Race Tempo',
        subtitle: 'Race pace. Hold it.',
        targetDistanceKm: 12,
        targetDurationMin: 64,
        targetCyclingDistanceKm: 26,
        targetCyclingDurationMin: 55,
        xpReward: 130,
      },
      {
        type: 'easy',
        title: 'Recovery Run',
        subtitle: 'Easy after the hard.',
        targetDistanceKm: 12,
        targetDurationMin: 64,
        targetCyclingDistanceKm: 26,
        targetCyclingDurationMin: 55,
        xpReward: 115,
      },
      {
        type: 'recovery',
        title: 'Pre-Race Flush',
        subtitle: 'Legs fresh for battle.',
        targetDistanceKm: 12,
        targetDurationMin: 64,
        targetCyclingDistanceKm: 26,
        targetCyclingDurationMin: 55,
        xpReward: 110,
      },
    ],
  },
  {
    index: 8,
    title: 'ENDURANCE PEAK',
    subtitle: 'Maximum aerobic range.',
    missionTemplates: [
      {
        type: 'long',
        title: 'Deep Zone March',
        subtitle: 'Longest run of the campaign.',
        targetDistanceKm: 13,
        targetDurationMin: 70,
        targetCyclingDistanceKm: 28,
        targetCyclingDurationMin: 60,
        xpReward: 140,
      },
      {
        type: 'interval',
        title: 'Speed Override',
        subtitle: 'Go to the well.',
        targetDistanceKm: 13,
        targetDurationMin: 70,
        targetCyclingDistanceKm: 28,
        targetCyclingDurationMin: 60,
        xpReward: 145,
      },
      {
        type: 'tempo',
        title: 'Lock Frequency',
        subtitle: 'Threshold held hard.',
        targetDistanceKm: 13,
        targetDurationMin: 70,
        targetCyclingDistanceKm: 28,
        targetCyclingDurationMin: 60,
        xpReward: 140,
      },
      {
        type: 'easy',
        title: 'Sector Patrol',
        subtitle: 'Active recovery run.',
        targetDistanceKm: 13,
        targetDurationMin: 70,
        targetCyclingDistanceKm: 28,
        targetCyclingDurationMin: 60,
        xpReward: 125,
      },
      {
        type: 'recovery',
        title: 'Zone Hold',
        subtitle: 'Recover smart, perform hard.',
        targetDistanceKm: 13,
        targetDurationMin: 70,
        targetCyclingDistanceKm: 28,
        targetCyclingDurationMin: 60,
        xpReward: 120,
      },
    ],
  },
  {
    index: 9,
    title: 'SPEED-STAMINA FUSION',
    subtitle: 'Fast over distance. The elite formula.',
    missionTemplates: [
      {
        type: 'interval',
        title: 'Alpha Surge',
        subtitle: 'Race intensity intervals.',
        targetDistanceKm: 14,
        targetDurationMin: 75,
        targetCyclingDistanceKm: 30,
        targetCyclingDurationMin: 64,
        xpReward: 150,
      },
      {
        type: 'long',
        title: 'Outer Zone Haul',
        subtitle: 'Go far. Stay focused.',
        targetDistanceKm: 14,
        targetDurationMin: 75,
        targetCyclingDistanceKm: 30,
        targetCyclingDurationMin: 64,
        xpReward: 145,
      },
      {
        type: 'tempo',
        title: 'Comm Domination',
        subtitle: 'Hold high output.',
        targetDistanceKm: 14,
        targetDurationMin: 75,
        targetCyclingDistanceKm: 30,
        targetCyclingDurationMin: 64,
        xpReward: 150,
      },
      {
        type: 'easy',
        title: 'Foundation Run',
        subtitle: 'Aerobic base solid.',
        targetDistanceKm: 14,
        targetDurationMin: 75,
        targetCyclingDistanceKm: 30,
        targetCyclingDurationMin: 64,
        xpReward: 130,
      },
      {
        type: 'recovery',
        title: 'Active Flush',
        subtitle: 'Regenerate. Reload.',
        targetDistanceKm: 14,
        targetDurationMin: 75,
        targetCyclingDistanceKm: 30,
        targetCyclingDurationMin: 64,
        xpReward: 125,
      },
    ],
  },
  {
    index: 10,
    title: 'ELITE CONDITIONING',
    subtitle: 'Performance at the highest level.',
    missionTemplates: [
      {
        type: 'long',
        title: 'Marathon Recon',
        subtitle: 'Close to marathon distance.',
        targetDistanceKm: 15,
        targetDurationMin: 80,
        targetCyclingDistanceKm: 32,
        targetCyclingDurationMin: 68,
        xpReward: 160,
      },
      {
        type: 'interval',
        title: 'Surge Crush',
        subtitle: 'Max power. Max return.',
        targetDistanceKm: 15,
        targetDurationMin: 80,
        targetCyclingDistanceKm: 32,
        targetCyclingDurationMin: 68,
        xpReward: 165,
      },
      {
        type: 'tempo',
        title: 'Full Frequency',
        subtitle: 'Sustained threshold.',
        targetDistanceKm: 15,
        targetDurationMin: 80,
        targetCyclingDistanceKm: 32,
        targetCyclingDurationMin: 68,
        xpReward: 160,
      },
      {
        type: 'easy',
        title: 'Grid Run',
        subtitle: 'Aerobic engine firing.',
        targetDistanceKm: 15,
        targetDurationMin: 80,
        targetCyclingDistanceKm: 32,
        targetCyclingDurationMin: 68,
        xpReward: 145,
      },
      {
        type: 'recovery',
        title: 'Peak Recovery',
        subtitle: 'Protect the peak.',
        targetDistanceKm: 15,
        targetDurationMin: 80,
        targetCyclingDistanceKm: 32,
        targetCyclingDurationMin: 68,
        xpReward: 140,
      },
    ],
  },
  {
    index: 11,
    title: 'CHAMPIONSHIP PROTOCOL',
    subtitle: 'Championship form achieved.',
    missionTemplates: [
      {
        type: 'interval',
        title: 'Championship Surge',
        subtitle: 'Everything you have.',
        targetDistanceKm: 16,
        targetDurationMin: 85,
        targetCyclingDistanceKm: 34,
        targetCyclingDurationMin: 72,
        xpReward: 175,
      },
      {
        type: 'long',
        title: 'Distance Command',
        subtitle: 'Control the long haul.',
        targetDistanceKm: 16,
        targetDurationMin: 85,
        targetCyclingDistanceKm: 34,
        targetCyclingDurationMin: 72,
        xpReward: 170,
      },
      {
        type: 'tempo',
        title: 'Signal Absolute',
        subtitle: 'Threshold locked in.',
        targetDistanceKm: 16,
        targetDurationMin: 85,
        targetCyclingDistanceKm: 34,
        targetCyclingDurationMin: 72,
        xpReward: 175,
      },
      {
        type: 'easy',
        title: 'Sector Clear',
        subtitle: 'Smooth and powerful.',
        targetDistanceKm: 16,
        targetDurationMin: 85,
        targetCyclingDistanceKm: 34,
        targetCyclingDurationMin: 72,
        xpReward: 155,
      },
      {
        type: 'recovery',
        title: 'Championship Recovery',
        subtitle: 'Recover like a champion.',
        targetDistanceKm: 16,
        targetDurationMin: 85,
        targetCyclingDistanceKm: 34,
        targetCyclingDurationMin: 72,
        xpReward: 150,
      },
    ],
  },
  {
    index: 12,
    title: 'ELITE COMPLETE',
    subtitle: 'The elite has arrived.',
    missionTemplates: [
      {
        type: 'long',
        title: 'Final Range',
        subtitle: 'Leave nothing behind.',
        targetDistanceKm: 18,
        targetDurationMin: 95,
        targetCyclingDistanceKm: 38,
        targetCyclingDurationMin: 80,
        xpReward: 190,
      },
      {
        type: 'interval',
        title: 'Victory Surge',
        subtitle: 'One last push. Make it count.',
        targetDistanceKm: 18,
        targetDurationMin: 95,
        targetCyclingDistanceKm: 38,
        targetCyclingDurationMin: 80,
        xpReward: 195,
      },
      {
        type: 'tempo',
        title: 'Final Frequency',
        subtitle: 'Signal locked. Zone restored.',
        targetDistanceKm: 18,
        targetDurationMin: 95,
        targetCyclingDistanceKm: 38,
        targetCyclingDurationMin: 80,
        xpReward: 190,
      },
      {
        type: 'easy',
        title: 'Zone Complete',
        subtitle: 'You earned this.',
        targetDistanceKm: 18,
        targetDurationMin: 95,
        targetCyclingDistanceKm: 38,
        targetCyclingDurationMin: 80,
        xpReward: 170,
      },
      {
        type: 'recovery',
        title: 'Elite Recovery',
        subtitle: 'Elite operatives rest smart.',
        targetDistanceKm: 18,
        targetDurationMin: 95,
        targetCyclingDistanceKm: 38,
        targetCyclingDurationMin: 80,
        xpReward: 165,
      },
    ],
  },
];

export const PERSONA_CAMPAIGNS: Record<PersonaId, CampaignTemplate[]> = {
  ghost: GHOST_CAMPAIGNS,
  scout: SCOUT_CAMPAIGNS,
  operative: OPERATIVE_CAMPAIGNS,
  elite: ELITE_CAMPAIGNS,
  vanguard: VANGUARD_CAMPAIGNS,
};

export const PERSONA_LABELS: Record<
  PersonaId,
  { label: string; description: string; icon: string }
> = {
  ghost: {
    label: 'RECRUIT',
    description: 'New to the field. Every step counts — walking or running.',
    icon: 'directions-walk',
  },
  scout: {
    label: 'SCOUT',
    description: 'Getting moving. Building consistency, one mission at a time.',
    icon: 'directions-run',
  },
  operative: {
    label: 'RUNNER',
    description: "You run regularly. Now it's about structure and progress.",
    icon: 'fitness-center',
  },
  elite: {
    label: 'ELITE',
    description: 'Strong endurance. Pushing limits and chasing performance.',
    icon: 'speed',
  },
  vanguard: {
    label: 'VANGUARD',
    description:
      'Top tier operative. Leading the field, mastering every mission.',
    icon: 'whatshot',
  },
};

export function getTotalCampaignXp(personaId: PersonaId): number {
  return PERSONA_CAMPAIGNS[personaId].reduce(
    (total, campaign) =>
      total + campaign.missionTemplates.reduce((s, t) => s + t.xpReward, 0),
    0,
  );
}

/**
 * Sum of template XP rewards for the first `campaignsCompletedCount` campaigns for this persona.
 * Used by display XP to reconcile persisted XP with campaign structure (see `getDisplayXpTotal`).
 */
export function getXpForCompletedCampaigns(
  personaId: PersonaId,
  campaignsCompletedCount: number,
): number {
  const list = PERSONA_CAMPAIGNS[personaId];
  if (!list?.length || campaignsCompletedCount <= 0) return 0;
  const n = Math.min(campaignsCompletedCount, list.length);
  let total = 0;
  for (let i = 0; i < n; i++) {
    const campaign = list[i]!;
    total += campaign.missionTemplates.reduce((s, t) => s + t.xpReward, 0);
  }
  return total;
}

/**
 * Expected missions, goal-met count, and distance from mission templates for the first
 * `campaignsCompletedCount` campaigns (used by profile stats when saves drift).
 */
export function getStatsFromCompletedCampaignTemplates(
  personaId: PersonaId,
  campaignsCompletedCount: number,
  activityMode: ActivityMode,
): { missions: number; missionsCompleted: number; distanceKm: number } {
  const list = PERSONA_CAMPAIGNS[personaId];
  if (!list?.length || campaignsCompletedCount <= 0) {
    return { missions: 0, missionsCompleted: 0, distanceKm: 0 };
  }
  const n = Math.min(campaignsCompletedCount, list.length);
  let missions = 0;
  let distanceKm = 0;
  for (let i = 0; i < n; i++) {
    for (const t of list[i]!.missionTemplates) {
      missions += 1;
      distanceKm +=
        activityMode === 'cycle'
          ? t.targetCyclingDistanceKm
          : t.targetDistanceKm;
    }
  }
  return {
    missions,
    missionsCompleted: missions,
    distanceKm,
  };
}
